### ISSUE TITLE
Scarb deps don't work when using Cairo test runner

### ISSUE THREAD

**Issue by Pet3ris** [software-mansion/scarb#105]
### Problem

Cairo test runner doesn't know how to pull in Scarb dependencies (building does work)

### Steps

1. Repo reproduction is here: https://github.com/auditless/cairo-template/issues/9.
2. Just need to uncomment the commented bits in Scarb config/code/tests if you want to run it).

### Possible Solution(s)

Wait for Protostar?

### Version

```text
scarb 0.1.0-alpha.2 (d5553ded6 2023-02-22)
cairo: 1.0.0-alpha.3
```
```

**Comment by mkaput** [comment]
Hey! Currently, I'd suggest waiting for Protostar to happen. Somewhen in next two weeks you can expect a veeery early release supporting testing pure-Cairo code, essentially covering `cairo-test-runner` feature set I believe.

Also, as a workaround, I suggest keeping `cairo_project.toml` file temporarily. You can manually update it to add Scarb-managed dependencies as crate root. The easiest way to gather locations is by taking a look at `scarb metadata` output.
