### ISSUE TITLE
Canonicalize Git URLs in scarb add

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#108]
We have a logic for canonicalization of Git URLs, primarily for GitHub. It's done by `CanonicalUrl` struct.

`scarb add` currently pastes Git URL to the manifest verbatim. In order to encourage consistent style of everything, I think it'd be nice to canonicalize these URLs that users are passing.

**Comment by kariy** [comment]
I'd like to work on this.

I assume the main thing here is to change the git url type to `CanonicalUrl`?

**Comment by mkaput** [comment]
Task is yours :)

**Comment by mkaput** [comment]
> I assume the main thing here is to change the git url type to `CanonicalUrl`?

Nope, I would rather construct CanonicalUrl running add operation in manifest-editor

**Comment by kariy** [comment]
but i assume just have to change it in [`GitSource`](https://github.com/software-mansion/scarb/blob/fe0b0cf6d28d2a6b985fc8dcc77f92bce663fcf4/scarb/src/manifest_editor/add.rs#L42), no?

**Comment by mkaput** [comment]
Yes, the string that goes in `git` field is to be canonicalized. I think if canonicalization fails, I would print a warning that this is not a URL, and leave it as-is.
