### ISSUE TITLE
"Go to Definition" won't work if the path of the project contains special string "&"

### ISSUE THREAD

**Issue by zsluedem** [software-mansion/scarb#1081]
### Problem

"Go to Definition" won't work if the path of the project contains special string "&"

### Steps

1. Create a project with "&" in the path
2. open a vscode on it
3. you can see error msg in output

### Possible Solution(s)

Didn't investigate.

### Version

```text
scarb --version
scarb 2.4.3 (5dbab1f31 2024-01-04)
cairo: 2.4.3 (https://crates.io/crates/cairo-lang-compiler/2.4.3)
sierra: 1.4.0
```

**Comment by mkaput** [comment]
Hey! This is a CairoLS bug. Can you please recreate this issue in https://github.com/starkware-libs/cairo? Thanks! :)
