### ISSUE TITLE
Update installation guide to include installing on windws subsystem for linux ( WSL) for windows users

### ISSUE THREAD

**Issue by quentin-abei** [software-mansion/scarb#1196]
### Problem

When using WSL on windows for coding, user needs to get through lot of steps to install scarb and get it working, and the installations guide is not up to date for that. I have written a guide for a smooth installation on wsl after doing it myself.
Here is my written tutorial, you may copy it and update the installation guide for WSL users on windows.

- Please note this will work for all scarb version , user just need to specify link to the desired github release during installation.

Iam using WSL Ubuntu distro , continue reading if you are also using WSL

first go to this link to find how to copy a github release link to your clipboard and copy the ```x86_64 linux scarb``` release file link [copy link to release](https://docs.github.com/en/repositories/releasing-projects-on-github/linking-to-releases)

Back to Ubuntu terminal
Download the Scarb release archive from the following link: [v0.1.0](https://github.com/software-mansion/scarb/releases/download/v0.1.0/scarb-v0.1.0-x86_64-unknown-linux-gnu.tar.gz)

You can use the following command to download the archive in your terminal:

```curl -L -o scarb.tar.gz https://github.com/software-mansion/scarb/releases/download/v0.1.0/scarb-v0.1.0-x86_64-unknown-linux-gnu.tar.gz```

replace everything after scarb.tar.gz with your link

then

```mkdir scarb```

Extract the contents of the archive to a location where you would like to have Scarb installed, e.g. ~/scarb. You can use the following command to extract the archive: ```tar -xf scarb.tar.gz -C ~/scarb --strip-components=1```

If you're using bash, you can add the following line to your ~/.bashrc file: ```export PATH="$PATH:~/scarb/bin"``` to do this open ~/.bashrc inside an editor , you can do ```nano ~/.bashrc``` or ```code ~/.bashrc``` then add the export PATH at the end of the file save then close your editor

Reload your shell configuration by running the following command in your terminal: ```source ~/.bashrc```

Open a new terminal and run ```scarb --version```

this command should print both scarb and cairo version scarb 0.1.0 (289137c24 2023-03-28) cairo: 1.0.0-alpha.6 to your console

### Proposed Solution

See above, i have written a tutorial

**Comment by maciektr** [comment]
Hi @quentin-abei !
Isn't this roughly what our installation script does though? 
Have you tried just installing with the help of the script? 
The docs for script usage are here: https://docs.swmansion.com/scarb/download.html#install-via-installation-script
Let me know if this doesn't work for you.

**Comment by quentin-abei** [comment]
Hello @maciektr , no I did not use the script
I believe my guide is worth adding for those who want to install manually by following a written guide .
Thanks

**Comment by maciektr** [comment]
Since this is basically equivalent to the installation script, which I assume works on WSL, I am against documenting this, as redundant. I believe that If someone has a specific reason to not use the script, they are capable of manual installation that suits their needs without a written guide.

**Comment by maciektr** [comment]
Closing as redundant - discussed above
