### ISSUE TITLE
Expected metadata resolve root to be `scarb`.

### ISSUE THREAD

**Issue by raghav-rama** [software-mansion/scarb#1248]
### Problem

Git clone [this](https://github.com/shramee/starklings-cairo1) repo and run `cargo build`
You will get the following error. Now I'm not sure why this comes, but it expects the root of the package to start with `scarb `
Is there some issue on my end or something else?
![image](https://github.com/software-mansion/scarb/assets/91389059/c2a31c18-d32b-4c8c-a444-f4add2e892e5)

```
OS: Ubuntu 22.04
Other relevant details:
scarb 2.6.3 (e6f921dfd 2024-03-13)
cairo: 2.6.3 (https://crates.io/crates/cairo-lang-compiler/2.6.3)
sierra: 1.5.0
cargo 1.77.1 (e52e36006 2024-03-26)
```

### Steps

1. Git clone https://github.com/shramee/starklings-cairo1
2. run `cargo build`

### Notes

I'm not sure why this comes, but it expects the root of the package to start with `scarb `

### Version

```text
scarb 2.6.3 (e6f921dfd 2024-03-13)
cairo: 2.6.3 (https://crates.io/crates/cairo-lang-compiler/2.6.3)
sierra: 1.5.0
```

**Comment by mkaput** [comment]
Hey! Downgrade Rust to 1.76. 1.77 broke our builds and a fix for this will be included in next Scarb release.
