### ISSUE TITLE
Generalize logic for parsing `-p` CLI argument

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#127]
https://github.com/software-mansion/scarb/blob/bb5c31e7d5f4ea04bb57df2036d485654f3c8c4c/scarb/src/bin/scarb/commands/add.rs#L13-L20

**Comment by kariy** [comment]
I would like to try this one. Can you provide more context on this?

**Comment by mkaput** [comment]
I am thinking of providing following thing in `scarb::args` (in CLI code):

```rust
struct PackagesFilter {
    package: String
}

impl PackagesFilter {
    pub fn match_one(&self, ws: &Workspace<'_>) -> Result<Package> { ... }
}
```

This type should be usable as the value type of all `args.package` field, i.e. should be parseable by Clap etc.

Cargo has something similar, but with globs and with less Clap-native interface [here](https://github.com/rust-lang/cargo/blob/c61b0f06807f3da60b7bbfa61455871d681e5eb5/src/cargo/ops/cargo_compile/packages.rs#L17).

I hope this should clarify everything :D Ping me if that's still something to elaborate on. The task is yours, thanks!
