### ISSUE TITLE
Keep scarb up to date in crates.io

### ISSUE THREAD

**Issue by edg-l** [software-mansion/scarb#1335]
### Problem

To use scarb as a dependency on other projects that want to publish on crates.io, we can't rely on using the git revision, since it requires specifying a version available on crates.io. 

Would it be possible to maintain the published crates up to date? 

Thanks in advance.

### Proposed Solution

Maintain the published crates up to date

**Comment by mkaput** [comment]
https://docs.swmansion.com/scarb/docs/writing-extensions/scarb-crate.html

**Comment by edg-l** [comment]
> You should not use Scarb as a crate: https://docs.swmansion.com/scarb/docs/writing-extensions/scarb-crate.html
> 
> The only project using `scarb` crate that we support is Dojo, and we're currently in the process of migrating them away from this.

well we are not using the scarb crate one, i meant the scarb-metadata and scarb-ui ones

**Comment by mkaput** [comment]
Hmm, both seem to be up-to-date. These two crates are pretty complete and stable and not a lot of stuff is happening there :)

**Comment by edg-l** [comment]
> Hmm, both seem to be up-to-date. These two crates are pretty complete and stable and not a lot of stuff is happening there :)
> 
> https://github.com/software-mansion/scarb/commits/main/scarb-metadata https://github.com/software-mansion/scarb/commits/main/utils/scarb-ui

i see, thanks!
