### ISSUE TITLE
Make queries from `DocGroup` take `DocumentableItem` as arg

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/scarb#1428]
Currently it takes `LookupItemId`, which doesn't allow `Member` and `Variant` to be passed.
Tagged with `// TODO(#1428)`

**Comment by piotmag769** [comment]
@wawel37 FYI it's done in the compiler
https://github.com/starkware-libs/cairo/blob/aa3865ea61c008e172992a8574311c94a98428e9/crates/cairo-lang-doc/src/db.rs#L18

Just need changes in Scarb when bumping Cairo

**Comment by maciektr** [comment]
@wawel37 isn't it done?

**Comment by piotmag769** [comment]
This is just done, no?
