### ISSUE TITLE
Set cairo version in manifest

### ISSUE THREAD

**Issue by tarrencev** [software-mansion/scarb#145]
### Problem

Contracts might be dependent on a particular version of the corelib

### Proposed Solution

Allow users to set the cairo corelib version to use in the Scarb manifest, providing a `rev` which could be a tag or commit hash

**Comment by mkaput** [comment]
Hey! This seems to duplicate #90. Closing this in favour of the original issue. It's a great suggestion to allow specifying a `rev` here!
