### ISSUE TITLE
Research adding support for `cairo` to mdbook

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/scarb#1457]
We can see how `cairo-book` did it, tagged with `// TODO(#1457`

**Comment by Arcticae** [comment]
This can also be added by defining a language for https://highlightjs.org/ - it's the mechanism that mdbook uses for syntax highlighting.
We could use fork [rust definition](https://github.com/highlightjs/highlight.js/blob/main/src/languages/rust.js) and modify it for cairo (shouldn't be too much of a problem), and then integrate it into mdbook - see [example implementation](https://github.com/pen-lang/pen/pull/395/files)

https://highlightjs.readthedocs.io/en/latest/language-guide.html
