### ISSUE TITLE
In a scarb workspace the flag `enable-gas` is ignored if is set in a package

### ISSUE THREAD

**Issue by FilipLaurentiu** [software-mansion/scarb#1479]
### Problem

In a workspace the flag `enable-gas` is ignored if is set in a package

### Steps

1. set `enable-gas` flag value in the package
```
[cairo]
enable-gas = false
```
2. `scarb build`
3. run the program with inputs 

```
cairo1-run ../target/dev/cli.sierra.json --layout recursive_with_poseidon \ 
    --air_public_input ../public_input.json \
    --air_private_input ../private_input.json \
    --trace_file trace \
    --memory_file memory \
    --proof_mode \
    --args '[..]`
```

> Error: Compilation(InvocationError { statement_idx: StatementIdx(1165), error: UnknownVariableData })

4. set `enable-gas` flag in the higher `Scarb.toml` workspace file
```
[cairo]
enable-gas = false
```

5. run the program with the same inputs without errors
```
cairo1-run ../target/dev/cli.sierra.json --layout recursive_with_poseidon \ 
    --air_public_input ../public_input.json \
    --air_private_input ../private_input.json \
    --trace_file trace \
    --memory_file memory \
    --proof_mode \
    --args '[..]`
```

### Version

```text
scarb 2.6.5 (d49f54394 2024-06-11)
cairo: 2.6.4 (https://crates.io/crates/cairo-lang-compiler/2.6.4)
sierra: 1.5.0
```

**Comment by maciektr** [comment]
Hi!

That's not really how it's intended to work. 

1) All keys that can be inherited are listed here https://docs.swmansion.com/scarb/docs/reference/workspaces.html
2) The `cairo` section is part of profile definition. 
3) In a workspace settings, profiles from workspace root (and only workspace root) are applied to all compiled packages. You can override the value in profile in workspace root manifest to use it across all packages. 

Wrapping up, to achieve what you want, in top level manifest you should add 
```
[profile.dev.cairo]
enable-gas = false
```
(or any other profile name that you use during compilation)

**Comment by FilipLaurentiu** [comment]
> Hi!
> 
> That's not really how it's intended to work.
> 
>     1. All keys that can be inherited are listed here https://docs.swmansion.com/scarb/docs/reference/workspaces.html
> 
>     2. The `cairo` section is part of profile definition.
> 
>     3. In a workspace settings, profiles from workspace root (and only workspace root) are applied to all compiled packages. You can override the value in profile in workspace root manifest to use it across all packages.
> 
> 
> Wrapping up, to achieve what you want, in top level manifest you should add
> 
> ```
> [profile.dev.cairo]
> enable-gas = false
> ```
> 
> (or any other profile name that you use during compilation)
> 
> Let me know if this helps!

So, just to make sure I explain it correctly. I have a workspace with multiple packages. In one of the packages I want to set the `enable-gas` flag to `false`. That was the way I use it before I had my project organized as a workspace, but it doesn't work like that anymore. In order to make it work I need to set the flag in the root manifest file.

Are you saying that this is the intended behavior and now I should use profiles for my package ?

**Comment by maciektr** [comment]
Yes, by design a workspace shares the compiler config across all compiled packages. You can have two profiles (with different compiler configuration) and build the specific package separately (`scarb build --profile nogas --package package_with_no_gas`) or just don't add it as part of the workspace.

**Comment by FilipLaurentiu** [comment]
> Yes, by design a workspace shares the compiler config across all compiled packages. You can have two profiles (with different compiler configuration) and build the specific package separately (`scarb build --profile nogas --package package_with_no_gas`) or just don't add it as part of the workspace.

Got it ! Thank you for clarifications :handshake: I will close this issue
