### ISSUE TITLE
Scarb throws an error while init

### ISSUE THREAD

**Issue by THenry14** [software-mansion/scarb#1503]
### Problem

From tg.
When using scarb 2.7.0 and trying to init in an empty directory, there is an error

```
$ scarb init
✔ Which test runner do you want to set up? · Starknet Foundry (default)
✔ Which test runner do you want to set up? · Starknet Foundry (default)
error: destination `/Users/m/projects/tmp/wot` already exists
help: use `scarb init` to initialize the directory
[ERROR] Failed to initialize a new project: `scarb` exited with error
Created package.
```

It seems that the runner is being set up twice, but let's investigate it closer.

### Version

```text
2.7.0
```

**Comment by maciektr** [comment]
Caused by too old snforge version. We only test against the latest snforge. Upgrade of snforge resolves the issue.
