### ISSUE TITLE
Support packaging cairo-plugins in Scarb

### ISSUE THREAD

**Issue by maciektr** [software-mansion/scarb#1527]
1. Handle packaging of `builtin = true` Cairo plugins - only manifest normalization 
2. Change package manifest normalization to include `cairo-plugin` section
3. Allow packaging if target=lib or cairo-plugin (not only lib)
4. Make sure verification runs for proc-macro plugins and builtin plugins
5. (maybe design doc?) Do we need to package rust code with `cargo package` first? Do we need Cargo.toml manifest normalization?

**Comment by THenry14** [comment]
Draft pull request opened here: https://github.com/software-mansion/scarb/pull/1586
It generally works for proc macros, but only with hardcoded paths. Things should definitely be refactored and improved.

**Comment by maciektr** [comment]
After this is done, integrate Foundry package uploads to CI
https://github.com/foundry-rs/starknet-foundry/pull/2461
https://github.com/foundry-rs/starknet-foundry/pull/2460
