### ISSUE TITLE
feat: `scarb fmt` option to target a specific file.

### ISSUE THREAD

**Issue by enitrat** [software-mansion/scarb#1534]
### Problem

# Describe the Feature Request

Following https://github.com/starkware-libs/cairo/issues/4134, for integration with external tools, cairo-format should have an option to take a specific file as a target, instead of formatting the entire package all at once.

For reference, with the old CairoZero cairo-format, we could do cairo-format ${target} which would format one specific file.
Forge (foundry) supports forge fmt ${target} --check as well. This works great for integration with lint aggregators.

# Describe Preferred Solution

Add an optional target argument, referring to the file to format. The command scarb fmt ${target} -e stdout should be valid. If a target is specfied, the name of the file being formatted is not part of the stdout.

cairo-format actually supports this; but scarb fmt doesn't: see below

```
❯ cargo run --bin cairo-format -- --help
Formats a file or directory with the Cairo formatter.
Exits with 0/1 if the input is formatted correctly/incorrectly.

Usage: cairo-format [OPTIONS] [FILES]...

Arguments:
  [FILES]...  A list of files and directories to format. Use "-" for stdin

Options:
  -c, --check                 Check mode, don't write the formatted files, just output the diff between the original and the formatted file
  -r, --recursive             Format directories content recursively
  -v, --verbose               Print verbose output
  -p, --print-parsing-errors  Print parsing errors
  -s, --sort-mod-level-items  Enable sorting the module level items (imports, mod definitions...)
  -h, --help                  Print help
  -V, --version               Print version
  ```
  
  However it's not shown when doing `scarb fmt --help`
  
  ```
  Usage: scarb fmt [OPTIONS]

Options:
  -c, --check                  Only check if files are formatted, do not write the changes to disk
  -e, --emit <EMIT>            Emit the formatted file to stdout [possible values: stdout]
  -v, --verbose...             Increase logging verbosity.
      --no-color               Do not color output
  -q, --quiet...               Decrease logging verbosity.
  -p, --package <SPEC>         Packages to run this command on, can be a concrete package name (`foobar`) or a prefix glob (`foo*`) [env: SCARB_PACKAGES_FILTER=] [default: *]
      --verbosity <VERBOSITY>  Set UI verbosity level by name. [env: SCARB_UI_VERBOSITY=]
  -w, --workspace              Run for all packages in the workspace
  -h, --help                   Print help
  ```
  
  Delegating this to the scarb team
  
  

### Proposed Solution

Either modify scarb fmt to accept a specific file path OR expose cairo-format through scarb (like scarb cairo-run does)

**Comment by ShantelPeters** [comment]
Please I will love to work on this

**Comment by maciektr** [comment]
@ShantelPeters assigning you then :D Good luck!

**Comment by ShantelPeters** [comment]
Thank you ser @maciektr i will get straight to work

**Comment by enitrat** [comment]
@maciektr is scarb fmt just a wrapper around cairo-format (like cairo-run) or is there a more complex logic to implement ?

**Comment by maciektr** [comment]
I'd say more complex. It's not a separate binary if that's what you mean, but Scarb built in. The implementation mainly lies here https://github.com/software-mansion/scarb/blob/main/scarb/src/ops/fmt.rs and is mainly based on `cairo_lang_formatter::CairoFormatter`

**Comment by maciektr** [comment]
Hi @ShantelPeters ! 
How is it going? Do you need any help?

**Comment by enitrat** [comment]
@maciektr I might take this later in the week unless you guys have some spare time ;p

**Comment by enitrat** [comment]
Finally took the time to implement this. Let me know how it is.
