### ISSUE TITLE
When defining a package as a internal dependency within workspace, dev-dependencies from both get included when compiling

### ISSUE THREAD

**Issue by cptartur** [software-mansion/scarb#1535]
### Problem

When defining a package as a internal dependency within workspace, dev-dependencies from both get included when compiling. This causes problems when using both cairo-test and starknet foundry in a single workspace.

### Version

2.7.0

**Comment by ShantelPeters** [comment]
Hi @cptartur please can I be assigned to this issue?

**Comment by ShantelPeters** [comment]
Okay sir @maciektr
