### ISSUE TITLE
Add `doc(hidden)` support

### ISSUE THREAD

**Issue by maciektr** [software-mansion/scarb#1572]
[] Support `doc(hidden)` 
[] Add `--document-hidden-items` that ignores `doc(hidden)`
[] Modify compiler plugins (e.g. `starknet`) to hide unnecessary documentation

**Comment by wawel37** [comment]
Moved the third point (Modify compiler plugins (e.g. starknet) to hide unnecessary documentation) to separate [task](https://github.com/software-mansion/scarb/issues/1610)
