### ISSUE TITLE
scarb doc generates Rust code blocks instead of Cairo ones

### ISSUE THREAD

**Issue by DelevoXDG** [software-mansion/scarb#1656]
`scarb doc` generates docs that have
````
```rust
````
code blocks.
Instead,
````
```cairo
````
code blocks should be generated.

Relevant logic on compiler side: https://github.com/wawel37/cairo/blob/40a7b60687682238f7f71ef7c59c986cc5733915/crates/cairo-lang-doc/src/markdown.rs#L29

**Comment by maciektr** [comment]
Duplicate of https://github.com/software-mansion/scarb/issues/1525#issuecomment-2326256994
