### ISSUE TITLE
maybe don't recompile `snforge_scarb_plugin` on every run I do

### ISSUE THREAD

**Issue by tdelabro** [software-mansion/scarb#1783]
### Problem

```shell
scarb test
     Running test s42_starknet_workshop (snforge test)
   Compiling snforge_scarb_plugin v0.33.0
    Finished `release` profile [optimized] target(s) in 0.06s
```
Every time I run my tests I have to wait for rust to try to compile `snforge_scarb_plugin`

### Proposed Solution

Don't try to compile it when the binary is already there

**Comment by piotmag769** [comment]
> 0.06s

It doesn't recompile anything as you can see, just checks if it has to.

**Comment by maciektr** [comment]
Closing, as explained by @piotmag769 in the previous comment
