### ISSUE TITLE
CairoRunner extension

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#242]
`scarb cairo-run -p package_name`, just like `cargo run`. Should use CairoRunner provided by the compiler

This should rather be an extension, perhaps bundled in default `scarb` distribution as for now. Not part of `scarb` crate, we do not want it to grow infinitely.

**Comment by enitrat** [comment]
small nitpick: the command should be `scarb cairo-run package_name` without the `-p` flag

**Comment by mkaput** [comment]
Why without `-p`? Scarb already uses `-p` in other places, and it follows Cargo behaviour this way :) See `cargo run --help`

**Comment by enitrat** [comment]
hm I see, I thought it could make more sense if it followed the `cairo-run` syntax, which doesn't use the `-p` flag

I'll leave it up to you! I'm fine with both but if it allows for more consistency with other commands then let's include it
