### ISSUE TITLE
Create GitHub Action which installs Scarb

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#245]
As the title says, it would be welcome to have something like [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) action

**Comment by milancermak** [comment]
Hey there!

I see this issue has been moved to the backlog, but not closed, so I assume you're still open to contributions? I have a minimal viable version of this ready. You can see it [in action here](https://github.com/milancermak/xoroshiro-cairo/actions/runs/5248067066/jobs/9479057891) - note the Install Scarb step. [This](https://github.com/milancermak/xoroshiro-cairo/pull/5/files#diff-29935151c4aca86cbb7602179f2f257dedf6947f34682556ea348a1c4be9d068) is how the action is declared.

It does not install the Rust toolchain, there already are GH acitons for that. I've successfully tested it with both `actions-rs/toolchain@v1` and `dtolnay/rust-toolchain@stable`. The action takes an optional `version` input. If left out, it installs the latest version, as per the install.sh script.

The [recommended way](https://docs.github.com/en/actions/creating-actions/about-custom-actions#choosing-a-location-for-your-action) of creating a public GH Action is to have it in a standalone repo. If you want to proceed forward, please create one and I can open a PR.

You can also reach me on Discord (`milan3774`) or TG (same handle as here) if you want to coordinate further.

Finally, I'm aware Marek is currently AFK, will wait for an answer.

**Comment by mkaput** [comment]
Hey @milancermak that's awesome! I would definitely like to "steal" your work, it's great 😍 I'll reach out to you on TG :)
