### ISSUE TITLE
Scarb only shows the help menu

### ISSUE THREAD

**Issue by ccolorado** [software-mansion/scarb#286]
### Problem

For some reason, scarb only returns the help dialog.
Deploy container from this [Dockerfile](https://github.com/ccolorado/starknet-pioneros-2023/blob/main/Dockerfile)
Dockerfile handles download, $PATH and installation on /root/bin/scarb from scarb-v0.1.0-x86_64-unknown-linux-gnu.tar.gz

I am taking part on a starknet bootcamp, and we are trying to simplify creating the dev environment for the attendees. Help is greatly appreciated. 

### Steps
```bash
# 1. Launch container
docker build --no-cache -t starknetes-cairo-goerli
docker run --detach -it --name starknetes_c1 starknetes-cairo-goerli
# 2. Connect to container
docker exec -it starknetes_c1 /bin/bash
```
### 3. Once connected, all and any command/option from scarb returns the help dialog (scarb --help)
* scarb new foobar
* scarb init 
* scarb --version

### Possible Solution(s)

Perhaps is an issue with the selected docker image,  but from what I can tell this configuration is consistently being used on the Starknet ecosystem

### Notes

Before installing these dependencies libc6-compat gcompat dependencies 
bash or shell reported scarb was not found, even when scarb was being called with its absolute path. 

### Version

```text
 v0.1.0-x86_64-unknown-linux-gnu
```

**Comment by mkaput** [comment]
Hey! Have you tried running this in non-Alpine image?

**Comment by ccolorado** [comment]
Yeah, tried it on Archlinux seems to work fine in there.

**Comment by mkaput** [comment]
👍🏻 I don't think we will support Alpine soon or ever, because while we technically don't use stuff that MUSL doesn't have -- we will probably will (and thus -- will have to target glibc) when we will implement compiler plugins

**Comment by ccolorado** [comment]
I see, thanks for clearing that out
