### ISSUE TITLE
scarb releases are not statically linked

### ISSUE THREAD

**Issue by cfal** [software-mansion/scarb#324]
### Problem

we are trying to use cairo and scarb Github releases in some of our build processes to save time, and although cairo Github releases are statically linked, scarb releases are not and only work in some environments:

```
        linux-vdso.so.1 (0x00007fff3eb56000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f33f6f4f000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f33f6f4a000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f33f6f45000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f33f5919000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f33f6f40000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f33f56f1000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f33f6f7b000)
```

### Possible Solution(s)

build scarb releases with musl, eg https://github.com/starkware-libs/cairo/blob/05867c82de42d5ee5cfa953dcca1cb826402f74b/.github/workflows/artifacts.yml#L14

**Comment by mkaput** [comment]
Hey! We are hesitant to publish, or at least commit to, musl builds, because Scarb is/is going soon to use quite more system-specific stuff and we are afraid we will hit incompatibility/behaviour issues between glibc and musl builds. I guess you're using Alpine in your build process? May I ask what are your reasons stopping you from using glibc-based distros?

I'd like to get to know user needs (musl support is a rare feature request as for now) before we decide whether we will commit to it 😄 

duplicates #286

**Comment by mkaput** [comment]
Hmm, for [compiler plugins as packages](https://github.com/software-mansion/scarb/discussions/227) we plan to end up dynamically building Rust code and using `dlopen` to load generated libraries. Won't this need extra support on your side anyway?

**Comment by mkaput** [comment]
> although that link mentions users must have rustup, vs users must have cargo and rustc - so maybe that would be an issue with the implementation you have in mind.

yes, that's one of things that I'm afraid of can be problematic for you; but on the other hand we didn't find a better solution to the general problem

> we currently have no problem building rust code, but for Github based projects that provide release binaries (and that aren't available on native package managers), we've been using them to speed up our compilation and release process... since this was the only release binary we came across that was dynamically linked, was hoping it could be resolved if not intentional 😄

We can publish musl builds starting with next Scarb version (it's a matter of uncommenting these lines: https://github.com/software-mansion/scarb/blob/main/.github/workflows/release.yml#L48-L51); but we will definitely not offer general support for these for a long time (until we will be sure that this will indeed work flawlessly when every potentially affected feature will be used by many people). Are you OK with that?
