### ISSUE TITLE
ASDF Plugin

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#384]
- [x] Decide whether to name the plugin `asdf-cairo` or `asdf-scarb`
- [x] Move to `software-mansion` org
- [x] Announce the plugin in ASDF plugins repository

**Comment by maciektr** [comment]
PR: https://github.com/software-mansion-labs/asdf-scarb/pull/1

**Comment by mkaput** [comment]
https://github.com/asdf-vm/asdf-plugins/pull/852
