### ISSUE TITLE
Add a command to clear the scarb cache

### ISSUE THREAD

**Issue by glihm** [software-mansion/scarb#411]
### Problem

I am not sure if it's a problem, but sometimes I don't know how my cache is populated with several versions of my repository.

For instance, I will have `myrepo-<random_string>/` and `myrepo-<random_string>`. I am about to dive in the code to understand this, but is that expected or not? Can it cause some troubles for scarb resolving and looking for the libraries?

### Proposed Solution

Is a command `scarb cache --clean` something that can make sense in the context of scarb? Or it's completly useless and there are no vulnerabilities/resolver problem having several versions of the same repo?

### Notes

Don't hesitate to close directly if it's not relevant. Thanks guys!

**Comment by maciektr** [comment]
Hi!
Those strings are not random. For instance, in case of git sources the value after package name is used to distinguish packages by remote urls. It shouldn't cause problems when resolving packages, as all calculations here are deterministic.

**Comment by glihm** [comment]
Thanks for the feedback @maciektr, very helpful info. :+1: I'll close then. Thanks!

**Comment by mkaput** [comment]
Reopening, because I still think that we could welcome a cache clear command. Perhaps `scarb clean --cache` ?

**Comment by glihm** [comment]
Sounds nice, this can be the way that a user can ensure everything is fetched again at the next `scarb build`.

This will then only clear the cache for the git dependencies for the manifest in the current directory? Because `scarb clean` is manifest dependent, right?

Because if cache is more global, as all projects are having their dependencies there, do you think it's better to have a `cache` dedicated command to ensure user is aware of what he is doing?

**Comment by mkaput** [comment]
> Because if cache is more global, as all projects are having their dependencies there, do you think it's better to have a `cache` dedicated command to ensure user is aware of what he is doing?

Yeah, that's what I mean. It's actually non-trivial to just clean what is needed by current workspace. Let's do `scarb cache clean` then :)

**Comment by glihm** [comment]
Let's go then!

Can I try this one to dive into Scarb code base?

**Comment by glihm** [comment]
Oh sorry no no if you've plan for it it's all good. 👍🏻 I'll look for an other one then. I am still discovering your code base.

**Comment by mkaput** [comment]
it's good, don't worry :) you can take this
