### ISSUE TITLE
Dependency resolution in Scarb.toml

### ISSUE THREAD

**Issue by neotheprogramist** [software-mansion/scarb#413]
### Problem

We can import alexandria_math and alexandria_encoding separately but not both.
Looks like an issue with dependency resolution because alexandria_encoding uses alexandria_math.

### Steps

Dependencies in Scarb.toml

Working:
[dependencies]
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria" }

Working:
[dependencies]
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria" }

NOT working:
[dependencies]
alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria" }
alexandria_math = { git = "https://github.com/keep-starknet-strange/alexandria" }

### Version

```text
scarb 0.4.0 (f813517bf 2023-06-06)
cairo: 1.1.0 (43b83560d)
```

**Comment by mkaput** [comment]
We'll take a look at that
