### ISSUE TITLE
Testing of package named keccak conflicts with corelib

### ISSUE THREAD

**Issue by enitrat** [software-mansion/scarb#417]
### Problem

I created a scarb package named `keccak`, was trying to run my own tests, but it was running tests from the `keccak_test.cairo` file.

### Steps

1. Create a new scarb package named keccak: `scarb new keccak`
2. Write a test function under `src/lib.cairo`
```
#[test]
fn test_scarb_keccak() {}
```
3. Run `scarb test`

### Version

```text
scarb 0.4.0 (f813517bf 2023-06-06)
cairo: 1.1.0 (43b83560d)
```

**Comment by maciektr** [comment]
Thanks for posting! 
I believe this is rather specific to the way `cairo-run` works. I have created an issue in Cairo repo to discuss if this behaviour is expected by the compiler team or not.

**Comment by mkaput** [comment]
Closing this in favour of https://github.com/starkware-libs/cairo/issues/3434
