### ISSUE TITLE
`scarb fetch`

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#487]
Just like `cargo fetch`, resolve the workspace (downloading all dependencies) ~and ensure lockfile is OK~. Basically do what `metadata` does without computing & printing the metadata.

**Comment by GianfrancoBazzani** [comment]
Hi, I would like to contribute, can I pick it?

**Comment by mkaput** [comment]
Hey! Yes, this task is yours now :) Mind that we don't have lockfiles yet, so this part is to be done in the future.
