### ISSUE TITLE
Investigate scarb cairo-run issues related to gas handling

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#495]
See this conversation: https://discord.com/channels/793094838509764618/1123235645083631626/1131497581147607092

**Comment by raphaelDkhn** [comment]
To summarize the conversation:

While using this [repository](https://github.com/gizatechxyz/orion_tutorials/tree/with-inference), an error was encountered when running the command `scarb cairo-run --available-gas 99999999999999999` to perform inference. The error message returned was:

```
mnist_nn % scarb cairo-run --available-gas 99999999999999999
running mnist_nn ...
Error: Failed calculating gas usage, it is likely a call for `gas::withdraw_gas` is missing.
error: process did not exit successfully: exit status: 1
```

However, when not using scarb and directly running `cairo-run . --available-gas 99999999999999999`, the operation works as expected. This scenario requires all the code from dependencies to be located in the same directory as it is not using scarb here.

**Comment by raphaelDkhn** [comment]
Awesome, thanks @maciektr 🙏

**Comment by maciektr** [comment]
Closing as superseded by #510
