### ISSUE TITLE
Enforce spacing in between function definition

### ISSUE THREAD

**Issue by ClementWalter** [software-mansion/scarb#516]
### Problem

The `scarb fmt` doesn't enforce a given number of lines between two functions. This means that both

```
fn a() {}

fn b() {}
```

```
fn a() {}


fn b() {}
```

are currently valid.

### Proposed Solution

Enforce either one or two lines spacing, but enforce!

**Comment by mkaput** [comment]
Hey! This is cairo-formatter issue, please report it here: https://github.com/starkware-libs/cairo

**Comment by ClementWalter** [comment]
see https://github.com/starkware-libs/cairo/issues/3824
