### ISSUE TITLE
Add a `--manifest-path` option on CLI commands

### ISSUE THREAD

**Issue by enitrat** [software-mansion/scarb#525]
### Problem

It would be nice to be able to pass the path to a `Scarb.toml` manifest file when running commands such as `scarb fmt` or `scarb build`. It allows us for more overall flexibility when using Scarb, e.g. for CIs

### Proposed Solution

Scarb CLI accepts a `--manifest-path <PATH>    Path to Scarb.toml` option

**Comment by enitrat** [comment]
Oops, just realised that it was actually possible to do something like

`scarb --manifest-path /path/to/Scarb.toml fmt`. I was trying to call `scarb fmt --manifest-path /path/to/Scarb.toml` instead,  interesting choice to have it before the subcommand

**Comment by mkaput** [comment]
> `scarb --manifest-path /path/to/Scarb.toml fmt`. I was trying to call `scarb fmt --manifest-path /path/to/Scarb.toml` instead, interesting choice to have it before the subcommand

That’s how Clap works 🤷 Global options must be before commands
