### ISSUE TITLE
scarb cairo-language-server hangs in VS Code

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#553]
### Problem

![image](https://github.com/software-mansion/scarb/assets/3450050/ac1fc0ee-ee99-4a3a-b781-9ce9aa15a4af)

> This same things is happening to me, and yes I'm using VSCode.
> I get the "Scarb is resolving the project" hanging forever, and the language-server doesn't work. You mentioned there is an issue with ASDF installation? I've been playing with the VSCode extension config, but it doesn't seem to work as expected, even removing the "use Scarb" option doesn't prevent the "Scarb is resolving the project"
> It never resolves, and if I reload the windows it starts another process, hanging as well.

### Notes

https://discord.com/channels/793094838509764618/1073222817195233412/1131342285905342605

### Version

```text
scarb 0.6.0
```

**Comment by mkaput** [comment]
I cannot reproduce this locally, waiting for sample repositories to test on...

**Comment by mkaput** [comment]
Several months have passed and we still did not get any reliable reproduction. Closing this as wontfix.

**Comment by Ifiora-Timothy** [comment]
> Several months have passed and we still did not get any reliable reproduction. Closing this as wontfix.

it hangs at "  0.006410099s  INFO cairo_lang_language_server: language server starting" and never starts in wsl on windows

**Comment by mkaput** [comment]
@Ifiora-Timothy have you tried investigating this further using these instructions: https://github.com/starkware-libs/cairo/tree/main/vscode-cairo#troubleshooting?

**Comment by Ifiora-Timothy** [comment]
> @Ifiora-Timothy have you tried investigating this further using these instructions: https://github.com/starkware-libs/cairo/tree/main/vscode-cairo#troubleshooting?

Yeah it works now.

Thank you
