### ISSUE TITLE
Allow building all contracts from dependency package at once

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#577]
### Problem

Some projects grew quite sizeable groups of contracts to include in `build-external-contracts` listing in their users. For instance, in Dojo, users have to include this behemoth in their projects:

```toml
[[target.dojo]]
build-external-contracts = [
    "dojo_erc::erc721::components::Balance",
    "dojo_erc::erc721::components::OperatorApproval",
    "dojo_erc::erc721::components::Owner",
    "dojo_erc::erc721::components::TokenApproval",
    "dojo_erc::erc721::erc721::ERC721",
    "dojo_erc::erc721::systems::erc721_approve",
    "dojo_erc::erc721::systems::erc721_burn",
    "dojo_erc::erc721::systems::erc721_mint",
    "dojo_erc::erc721::systems::erc721_set_approval_for_all",
    "dojo_erc::erc721::systems::erc721_transfer_from",
]
```

Missing one of the contracts here will lead to problems.

### Proposed Solution

Allow the `build-external-contracts` field to allow pulling all contracts from a given package/crate at once, in a glob fashion.

The expected syntax would look like this:

```toml
[[target.dojo]]
build-external-contracts = [
    "dojo_erc::*",
]
```

If this happens to be trivial to implement, it would be cool to also allow importing all contracts prefixed by a module. **But this is not mandatory, and just pulling everything from a crate is sufficient.** For instance:

```toml
[[target.dojo]]
build-external-contracts = [
    "dojo_erc::erc721::*",
]
```

### Notes

- The `dojo` target in this example inherits source code from `starknet-contract`. This task is about adding this logic to `starknet-contract`.
- The following parts of code will require amending:
    - https://github.com/software-mansion/scarb/blob/bf927194941f6c0ce62677e7e2ef4f9122489ff6/scarb/src/compiler/compilers/starknet_contract.rs#L69-L92
    - https://github.com/software-mansion/scarb/blob/bf927194941f6c0ce62677e7e2ef4f9122489ff6/scarb/src/compiler/compilers/starknet_contract.rs#L300-L325
    - ➕ I guess somewhere else
- Don't forget about adding tests!

---

Please leave a comment that you are willing to contribute a PR fixing this issue before starting doing so, in order to avoid having two people working on this independently 😄

**Comment by mkaput** [comment]
@tarrencev what do you think about this proposed syntax (with `*` usage)? Scarb team uniformly likes it :)

**Comment by ametel01** [comment]
I’d like to take this

**Comment by mkaput** [comment]
Go on :) Do you have any questions right now?

**Comment by ametel01** [comment]
> Go on :) Do you have any questions right now?

Yes, could you point me to any external examples?

**Comment by mkaput** [comment]
The docs and the example there are the only use case that we directly aimed for: https://docs.swmansion.com/scarb/docs/extensions/starknet/contract-target.html#compiling-external-contracts

As in issue description, this feature is used by Dojo. Here is the only example I could find: https://github.com/dojoengine/dojo/blob/9774d4b3670733636485d8e7bbee6801a8d7b925/examples/ecs/Scarb.toml#L13-L25. Dojo is maintaining a copy-paste or our code FYI
