### ISSUE TITLE
Disallow upper case letters in package names

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#591]
### Problem

We think we should stop allowing uppercase letters in package names:
1. Allowing both `foo` and `Foo` packages to exist may be dangerous.
2. Package names must be valid & idiomatic Cairo module names, and these are `snake_case`.
3. We copied current behaviour from Cargo, and it allows upper case only because it didn't care earlier. Rust [RFC 430](https://github.com/rust-lang/rfcs/blob/master/text/0430-finalizing-naming-conventions.md) established `snake_case` to be the way to go for crates, though Cargo packages are still [unclear](https://github.com/rust-lang/api-guidelines/discussions/29#discussioncomment-6659367).

### Proposed Solution

Make Scarb reject uppercase letters in package names. To do that, patch the [`PackageName` struct](https://github.com/software-mansion/scarb/blob/e9078ddfc5cf766dee8ab1054b911d204af73170/scarb/src/core/package/name.rs#L43-L83). Don't forget about tests. Also, please make a special condition for this that will print a tailored error message, guiding users what to do in order to fix it.

**Comment by glihm** [comment]
Definitely worth it. Having more consistency and homogeneity among packages is an important step toward automation, meta-programming etc...

Sure for people already having upper-case packages this will be a bit of work, but as you mentioned, guiding them should be fine to achieve a nice consistency among packages. :+1:
