### ISSUE TITLE
Make Scarb preserve terminal colors of arbitrary scripts

### ISSUE THREAD

**Issue by Chepelau** [software-mansion/scarb#598]
### Problem

Currently, when defining arbitrary scripts in `Scarb.toml` (for example `test = 'snforge'`), Scarb does not retain the original output colors. 

Scarb.toml: 
```
[package]
name = "bug_project"
version = "0.1.0"

[scripts]
test = 'snforge'
```
Running `snforge` : 
![image](https://github.com/software-mansion/scarb/assets/87245280/06099f73-fe3d-46e2-9292-7e7e08056aed)

Running `scarb test` (test is defined as snforge): 
![image](https://github.com/software-mansion/scarb/assets/87245280/937b1151-efd5-4ccc-8f81-7679462cbd17)

### Proposed Solution

Make Scarb preserve the colors.

**Comment by Chepelau** [comment]
Actually I went back and tried to define some other script that would print colored text, ie: `foo = "python3 -c \"print('\\033[94mThis text is colored.\\033[0m')\""`. In this case the text is indeed colored: 
![image](https://github.com/software-mansion/scarb/assets/87245280/9425744e-0ad2-40d5-8336-de73d161dcd5)

Other example: `proto = 'protostar test'`
Running protostar test is completely useless now but it does produce colored text:
![image](https://github.com/software-mansion/scarb/assets/87245280/c41a1aa6-fb31-4cff-814d-015a2dec40c6)

And as you can see Scarb again preserves the colors. 
So it is possible the issues is only with snforge.

**Comment by mkaput** [comment]
There is a slight chance we pass wrong environment variables and forge thinks it’s being piped to non-interactive tty. Let me know if you’ll get more insight

**Comment by Chepelau** [comment]
So unfortunately I wasn't able to pinpoint the exact reason why scarb makes snforge turnoff the colors, however to turn them on, it is enough to add following envars to `get_env_vars` function in `src/ops/subcommands.cairo`: 
```
        ("CLICOLOR".into(), "1".into()),
        ("CLICOLOR_FORCE".into(), "1".into()),
```
These envs are used by `console` crate that is used by snforge. 

This solution is might be slightly dirty  but if it works for you then I can make a PR.

**Comment by mkaput** [comment]
Does it work with `CLICOLOR` alone? I think it should be okay to inherit https://docs.rs/console/latest/console/fn.colors_enabled.html there

**Comment by Chepelau** [comment]
Unfortunately it does not work with `CLICOLOR` alone

**Comment by mkaput** [comment]
Force-enabling colours seems to me like an antipattern, and our context is not something this env var was designed for. I am almost certain what we should do here is to ensure that `isatty` works for stdin in Scarb's subprocesses, because that's probably where the bug lies.
