### ISSUE TITLE
Specify source directory other than `src`

### ISSUE THREAD

**Issue by delaaxe** [software-mansion/scarb#617]
### Problem

Allowing to specify the source folder as `.` instead of `src` would be especially helpful for workspace projects with a lot of packages where having that extra `src` folder in every package is a bit clunky and counter productive, see screenshot:

<img width="184" alt="Screenshot 2023-08-25 at 15 44 03" src="https://github.com/software-mansion/scarb/assets/1091900/77cc21e8-a6ea-4b6b-9b53-a3442292057b">

**Comment by maciektr** [comment]
Hi,

Thanks for feedback!

This actually duplicates #173, so I will close this issue now, but we will review your concerns when working on that.
