### ISSUE TITLE
🐛 Memory leak with scarb-cairo-language-server

### ISSUE THREAD

**Issue by Bal7hazar** [software-mansion/scarb#624]
### Problem

Since the version 0.7.0 of scarb (bringing cairo 2.2.0) I got an expansive usage of the memory until a total freeze.

### Steps

1. Install the latest version of scarb (0.7.0)
2. Clone this repository: https://github.com/carbonable-labs/cairo-erc-2981 and open VSCode
3. Open a task manager on the side and the Output tab in VSC and track `scarb-cairo-language-server`
4. Open the file at `src/components/ercc2981/interface.cairo` and leave scarb sync
5. Create a new empty interface at the end of the file:

```cairo
#[starknet::interface]
trait TestTrait<TContractState> {
}
```

Note: The Memory usage must be around 800Mo

6. Add a new method in the interface and observe the memory usage increasing by 3-10Mo per method added, such as:

Memory: `798.6Mo`

```cairo
#[starknet::interface]
trait TestTrait<TContractState> {
    fn test01(self: @TContractState) -> u256;
}
```

Memory: `802.3Mo`

```cairo
#[starknet::interface]
trait TestTrait<TContractState> {
    fn test01(self: @TContractState) -> u256;
    fn test02(self: @TContractState) -> u256;
}
```

Memory: `806.5Mo`

etc.

Note: Removing the previous methods doesn't release memory (it increase but not significantly)
Note: The Cairo-Language-Server Ouput tab doesn't log anything while adding code.
Note: This example shows an reasonable increase of the memory however while writing a whole implementation use significant amount of code, it results in reaching 10Go in few minutes.

### Version

```text
scarb 0.7.0 (58cc88efb 2023-08-23)
cairo: 2.2.0 (https://crates.io/crates/cairo-lang-compiler/2.2.0)
sierra: 1.3.0
```

EDIT (08/31): Update steps to reproduce

**Comment by mkaput** [comment]
Hey! Is this happening consistently (if not, then it's probably #553)? Are you able to send us the project which is causing this behaviour for you?

**Comment by Bal7hazar** [comment]
Memory usage always raise consistently, but the increase speed is not consistent, sometimes I can devlop for few hours before it freeze, sometimes just 10 minutes.

I'm working on this project rn and got the issue: https://github.com/Bal7hazar/carbon-protocol/tree/153-upgrade-protocol-to-cairo-10

I'll try to see if it also happen on a smaller project.

**Comment by mkaput** [comment]
We'll assign somebody to investigate that, next week I guess

**Comment by Bal7hazar** [comment]
@mkaput I updated the steps with a reproductible example

**Comment by mkaput** [comment]
Closing this in favour of: https://github.com/starkware-libs/cairo/issues/4062
