### ISSUE TITLE
Can’t build on an airplane

### ISSUE THREAD

**Issue by delaaxe** [software-mansion/scarb#647]
### Problem

If an http dependency doesn’t have a tag/commit specified, but it’s already cloned locally, just use the existing repo instead of failing with a network error?

**Comment by maciektr** [comment]
Hi!
Have you tried running with `--offline` flag?
E.g. 
```
scarb --offline build
```
or 
```
SCARB_OFFLINE=true scarb build
```


Currently, scarb tries to fetch the latest available revision of the dependency which will check after introduction of lockfiles tracked by https://github.com/software-mansion/scarb/issues/126
