### ISSUE TITLE
Support silencing Ui with clap verbosity quiet

### ISSUE THREAD

**Issue by maciektr** [software-mansion/scarb#65]
### Problem

The main cli arguments 
https://github.com/software-mansion/scarb/blob/afbbedd453cd1c362c5520f927648b7fec1776f0/scarb/src/bin/scarb/main.rs#L17 accept verbosity flag https://github.com/software-mansion/scarb/blob/afbbedd453cd1c362c5520f927648b7fec1776f0/scarb/src/bin/scarb/args.rs#L24 as defined by `clap-verbosity-flag` package. The flag is currently used for filtering tracing info.  
I suggest silencing the Ui interface https://github.com/software-mansion/scarb/blob/afbbedd453cd1c362c5520f927648b7fec1776f0/scarb/src/ui/mod.rs#L36 when the verbosity flag is set to silence ([is_silent](https://docs.rs/clap-verbosity-flag/latest/clap_verbosity_flag/struct.Verbosity.html#method.is_silent)).

**Comment by mkaput** [comment]
Fixed in a1e570cffa1aeab701738c58df772f695dbd4933
