### ISSUE TITLE
`scarb add` fetches dependencies from git with `--offline` flag

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/scarb#673]
### Problem

`scarb add` tried to pull dependency from git even if `--offline` flag is set.

### Steps

1. Run `scarb --offline add ...`

### Version

0.7.0

**Comment by mkaput** [comment]
Fetching from Git is an expected behaviour, see also #98 

Ignoring the `--offline` flag is a problem though!

**Comment by piotmag769** [comment]
Actually my bad on that, the `--offline` flag works 🤦 The issue is on our side, sorry :c

**Comment by rsodre** [comment]
> Actually my bad on that, the `--offline` flag works 🤦 The issue is on our side, sorry :c Feel free to close this one

And what was the issue on your side, how did you solve it?
--offline never worked for me.

**Comment by piotmag769** [comment]
@rsodre nothing rly, `scarb add --offline` just works for me
