### ISSUE TITLE
`scarb add` displays a missleading error message

### ISSUE THREAD

**Issue by piotmag769** [software-mansion/scarb#674]
### Problem

`scarb add` keeps added version when using registry package (that does not exist). Probably the real problem is the error message "cannot find package XYZ" instead of "package XYZ found but with version ABC" or sth like that

### Steps

1. `scarb add snforge_std@1.0.0`
2. `scarb add snforge_std --git https://github.com/foundry-rs/starknet-foundry.git`

error: cannot find package snforge_std

### Version

scarb 0.7.0 (58cc88efb 2023-08-23)
cairo: 2.2.0 (https://crates.io/crates/cairo-lang-compiler/2.2.0)
sierra: 1.3.0

**Comment by mkaput** [comment]
Seems like this duplicates #98
