### ISSUE TITLE
Add a `--emit stdout` flag to `scarb fmt`

### ISSUE THREAD

**Issue by ClementWalter** [software-mansion/scarb#700]
### Problem

There is no way to have scarb outputs the formatted result instead of overwriting the input.

This is a problem when integrating scarb with other linters in a tool like trunk.io. See [this file](https://github.com/ClementWalter/kakarot/blob/7686fbf022d99ce01927eb488ad59f0a0ec7ce5d/.trunk/trunk.yaml#L30) using `cairo-format`: 

https://github.com/ClementWalter/kakarot/blob/7686fbf022d99ce01927eb488ad59f0a0ec7ce5d/.trunk/trunk.yaml#L30

### Proposed Solution

Add, like in the previous `cairo-format` tool, or in `rustfmt` a flag `--emit stdout` to emit and not overwrite

**Comment by ClementWalter** [comment]
created issue in cairo https://github.com/starkware-libs/cairo/issues/4134

let's see what they are up to, imho just updating the behavior of `--check` is the easier

**Comment by orizi** [comment]
the handling of the output is done in the wrapping binary - not in the cairo library itself.
so there's no actual upstream updates required.

**Comment by Eikix** [comment]
I'd like to take this issue if possible

> the handling of the output is done in the wrapping binary - not in the cairo library itself. so there's no actual upstream updates required.

I'm not sure I understand this, what is the "wrapping binary", are you referring to a part of Scarb's system?

After talking with @ClementWalter, I propose this change:
- Change `scarb fmt --check` outputting a file diff to output a new file altogether. This is in accordance with the [Trunk](https://docs.trunk.io/check/custom-linters) documentation about custom linters and more generally with the `rewrite` norm of linting.
<img width="822" alt="image" src="https://github.com/software-mansion/scarb/assets/66871571/20af8c01-2fc8-4dad-8f78-597bb8e26e1a">

**Comment by mkaput** [comment]
> * Change `scarb fmt --check` outputting a file diff to output a new file altogether. This is in accordance with the [Trunk](https://docs.trunk.io/check/custom-linters) documentation about custom linters and more generally with the `rewrite` norm of linting.

I would definitely not deviate from `rustfmt` behaviour. It prints diffs so that the output is readable and actionable when somebody is reading CI logs. No reason to change that.

Please implement `--emit stdout` behaviour, like @ClementWalter suggested in the issue description.

---

The issue is yours 😉

**Comment by Eikix** [comment]
So if I understand correctly,
I should:
- inside `scarb fmt` related logic, add a flag "emit", with a single option "stdout" (for now).
- the emit flag with the option will emit a "target" file, fully formatted. with the option stdout, it'll emit it to stdout

-> no changes are made to cairo format
-> no changes are made to --check command

**Comment by mkaput** [comment]
Yep!
