### ISSUE TITLE
bug: unable to use bool as value in Felt252Dict

### ISSUE THREAD

**Issue by Th0rgal** [software-mansion/scarb#711]
### Problem

From my understanding of the cairo-book we can build a Dict with felt252 keys and any type for values, but when I try to use bool (for example) as values, it doesn't work:
This code runs smoothly:
```rs
let mut circular_lock: Felt252Dict<felt252> = Default::default();
```
But this one crashes
```rs
let mut circular_lock: Felt252Dict<bool> = Default::default();
```
Here is the log from scarb:
```
     Running cairo-test referral
testing referral ...
thread 'main' panicked at 'Got failure while specializing type.: TypeSpecialization { type_id: GenericTypeId("Felt252Dict"), error: UnsupportedGenericArg }', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cairo-lang-sierra-generator-2.2.0/src/db.rs:197:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process did not exit successfully: exit status: 10
```

### Steps

```
git clone git@github.com:starknet-id/referral_contract.git
cd referral_contract
git checkout acf032a9132052505b42a0a7cfe6ab7198c41769
scarb fetch
scarb test
```

### Notes

``circular_lock`` is defined line 131 of ``referral.cairo``
It is tested in `scr/tests/test_referral.cairo` line 368 in test ``test_add_rec_circular_commission``

### Version

```text
scarb 0.7.0 (58cc88efb 2023-08-23)
cairo: 2.2.0 (https://crates.io/crates/cairo-lang-compiler/2.2.0)
sierra: 1.3.0
```
```

**Comment by maciektr** [comment]
Hi @Th0rgal !

This error does not seem to relate to Scarb. We do not maintain the Cairo compiler. 

Please submit this issue in the compiler repository.
https://github.com/starkware-libs/cairo/
