### ISSUE TITLE
Support dev-dependencies 

### ISSUE THREAD

**Issue by maciektr** [software-mansion/scarb#717]
### Problem

Internally, manifest dependencies can define target kind. Allow reading dev-dependencies (for test targets) from manifest.  

### Proposed Solution

- Add `dev-dependencies` field to [`TomlManifest`](https://github.com/software-mansion/scarb/blob/3ba70df198efbfe5b36a7f25d1bb5a4d16ab0d71/scarb/src/core/manifest/toml_manifest.rs#L40). Note, that `TomlManifest` represents the toml structure of Scarb manifest files. The `dev-dependencies`, similarly to `dependencies` should allow inheriting dependency specification from workspace manifest via `MaybeTomlWorkspaceDependency` pattern (this translates to an enum, that accepts either dependency specification, or `workspace = true`, all under `MaybeWorkspace` type). This inheritance will be resolved later on (see `to_manifest` for reference). 
- Update [`TomlManifest::to_manifest`](https://github.com/software-mansion/scarb/blob/3ba70df198efbfe5b36a7f25d1bb5a4d16ab0d71/scarb/src/core/manifest/toml_manifest.rs#L366) function, to take `dev-dependencies` into account. Note, that this function is responsible for translating toml-based structure of manifest files, to our internal representation - `Manifest`. 
- To do that, you will need to parse `dev-dependencies` similarly to [`dependencies`](https://github.com/software-mansion/scarb/blob/3ba70df198efbfe5b36a7f25d1bb5a4d16ab0d71/scarb/src/core/manifest/toml_manifest.rs#L409) field. First, workspace inheritance is resolved, then the `TomlDependency`, which represents dependency spec in toml format is translated to `ManifestDependency`, which is our internal dependency specification representation, via `to_dependency` (note this is analogous to `TomlManifest`, `Manifest` and `to_manifest` flow described before). 
- Parsed `dev-dependencies` spec can be passed to a single vector of dependencies, together with `dependencies`.  The `ManifestDependency` struct (i.e. the parsed, internal representation of dependency specification) has a `kind` field, storing an enum called `DepKind`. This enum can be either `Normal` - meaning dependencies that are always included in the compilation unit, or `Target(TargetKind)`, which specifies that this dependency should only be included in compilation of a single target kind. 
- Please modify `to_dependency` so that you can define a dependency kind and set it to `test` target for all the `dev-dependencies`. Note, that you can use `kind` method on `ManifestDependency` builder.   
- When you pass a vector of dependencies, with appropriate dependency kind specification, the resolver will take care of plugin them in for appropriate builds - you should be good to go!

### Notes

Take a look at [Scarb core data model graph](https://github.com/software-mansion/scarb/blob/main/ARCHITECTURE.md#core-data-model) for more insight on relations between Scarb internals.

**Comment by MaksymilianDemitraszek** [comment]
It would be quite useful for starknet foundry to have it so people can move forge std there.
