### ISSUE TITLE
Building and testing are very slow

### ISSUE THREAD

**Issue by Th0rgal** [software-mansion/scarb#773]
### Problem

I used to use scarb `2.2.0` because I was told `2.3.0-rc0` was slow. I saw in the changelogs from `2.3.0-rc1` that it was faster. I installed it and updated my repository starknet dependency version but I can't build my project.  It doesn't produce errors, it just takes forever. Same when I want to test it.

### Steps
```
git clone git@github.com:starknet-id/naming.git
cd naming
git checkout refactor/resolving
scarb build
scarb test
```

### Version

```text
scarb 2.3.0-rc1 (00cfeddda 2023-10-09)
cairo: 2.3.0-rc0 (https://crates.io/crates/cairo-lang-compiler/2.3.0-rc0)
sierra: 1.3.0
```

**Comment by maciektr** [comment]
Hi @Th0rgal!

Thanks for submitting your issue!

Unfortunately, it seems to me that you have encountered a Cairo compiler bug. 

This behaviour seems to be the same on Cairo cli tools, Scarb workspace resolution works as expected and tracing logs from Cairo compiler seem suspicious to me.

Would you mind moving this issue to https://github.com/starkware-libs/cairo/issues for Cairo compiler team to investigate?
