### ISSUE TITLE
 No json file is generated using “scarb build”

### ISSUE THREAD

**Issue by zyunzh** [software-mansion/scarb#788]
I configured the scarb.toml file, but the [target name]_[contract name].contract_class.json file was not generated. Only the hello.starknet_artifacts.json file was in the target/dev folder.
`[package]
name = "hello"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[[target.starknet-contract]]
sierra = true

[dependencies]
starknet = ">=2.2.0"
# foo = { path = "vendor/foo" }`

**Comment by chan-bing** [comment]
Hi., I just use lib.scarb's own code after “scarf new xxx”

**Comment by chan-bing** [comment]
Oh i see。Thank you very much!
