### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by delaaxe** [software-mansion/scarb#801]
### Problem

What if SW releases Cairo `2.3.0-rc1` (currently doesn't exist), what will the scarb version be? Maybe you should use a different scheme for scarb fixes on a identical cairo version, maybe `2.3.0-rc0-patch1` or something

<img width="668" alt="Screenshot 2023-10-18 at 12 28 52" src="https://github.com/software-mansion/scarb/assets/1091900/f5e60a2b-ddc7-4205-832f-7cb663365b45">

**Comment by mkaput** [comment]
Starkware won't create `rc1`, our teams on synchronizing on this. The next compiler version will be `rc2`
