### ISSUE TITLE
Compile contracts under cfg(test) for foundry tests

### ISSUE THREAD

**Issue by maciektr** [software-mansion/scarb#847]
Starknet-foundry relies on Scarb's `starknet-contract` target to compile contracts that can be used during test runtime. There is a use case for foundry's users to create contracts only for this purpose. Such contracts could be defined either in test files, or under `cfg(test)` attribute.  As of now, Scarb does not have any interface that would enable foundry to compile them. 
cc @MaksymilianDemitraszek

**Comment by mkaput** [comment]
I think this could lead to smearing too much abilities everywhere. Why not just establishing a pattern to write contracts in separate packages and focus on implementing #717 instead?

**Comment by maciektr** [comment]
Decided to go with #717 instead

**Comment by maciektr** [comment]
https://github.com/foundry-rs/starknet-foundry/issues/471
