### ISSUE TITLE
What is the reason? Can you help me solve it?

### ISSUE THREAD

**Issue by my-Gem** [software-mansion/scarb#880]
### Problem

   Updating git repository https://github.com/openzeppelin/cairo-contracts
error: failed to fetch into: C:\Users\18431\AppData\Local\swmansion\scarb\cache\registry\git\db\cairo-contracts-9cboa8jg3jldq.git

Caused by:
    process did not exit successfully: exit code: 128

**Comment by mkaput** [comment]
Hey! Run `scarb -vvv fetch`. It will pipe `git` command call output to logs. Let me know if that helps :)
