### ISSUE TITLE
Why does cairo not compile when using scarb build?

### ISSUE THREAD

**Issue by my-Gem** [software-mansion/scarb#889]
### Problem

Some cairo files are not compiled through the scarb build command?

**Comment by maciektr** [comment]
Hi @my-Gem!

WDYM by "some files"? 
Are they skipped, or has some error been returned?

All your files have to be part of the package you are compiling.

**Comment by my-Gem** [comment]
There is no error in the terminal printing, but there is a cairo file that has not been compiled.

**Comment by maciektr** [comment]
Would you mind sharing a reproduction? Is this file included in your package (i.e. from lib.cairo downwards)?

**Comment by my-Gem** [comment]
Thank you very much, I solved this problem, but I encountered a new problem
![Uploading 2023-11-10_131733.jpg…]()

**Comment by my-Gem** [comment]
Thank you very much. I have solved the above problem, but I have encountered a new problem. Can you answer it?
![2023-11-10_131733](https://github.com/software-mansion/scarb/assets/26290087/d6a934a8-d15d-46df-9146-4de943450ede)

**Comment by maciektr** [comment]
Hi @my-Gem! 
I don't really think it is a Scarb issue per se. This seems like the problem in your cairo code. 

Would you mind trying following resources instead? I think you would get the best aligned help this way.
- https://book.cairo-lang.org/
- https://github.com/shramee/starklings-cairo1
- Support channel on discord https://discord.gg/qypnmzkhbc
