### ISSUE TITLE
Allow providing custom `core` version

### ISSUE THREAD

**Issue by mkaput** [software-mansion/scarb#90]
1. Stabilize `no-core` field in the manifest, i.e. document it properly.
2. If the main package of a compilation unit has `no-core = true`, then make sure the compilation unit has no implicit `core` package in its components, and instead require the main package to provide custom `core` dependency.

**Comment by tarrencev** [comment]
When specifying the dependency

```
[dependencies]
core = "100.0.0"
```

```
thread 'main' panicked at 'not yet implemented: Registry sources are not implemented yet.', /Users/tarrence/.cargo/git/checkouts/scarb-831c32bf23da0a7c/7f5ee8c/scarb/src/core/source/id.rs:216:37
```

When doing

```
[dependencies]
core = { git = "https://github.com/starkware-libs/cairo.git" }
```

```
    Updating git repository https://github.com/starkware-libs/cairo
     Running git fetch --verbose --force --update-head-ok https://github.com/starkware-libs/cairo +HEAD:refs/remotes/origin/HEAD
     Running git clone --local --verbose --config core.autocrlf=false --recurse-submodules /Users/tarrence/Library/Caches/com.swmansion.scarb/registry/git/db/cairo-U23CFPMK1656G.git /Users/tarrence/Library/Caches/com.swmansion.scarb/registry/git/checkouts/cairo-U23CFPMK1656G/1fe2c336
     Running git reset --hard 1fe2c3368262ee579cc7e58703217407d41b4514
Error: cannot find package core
```

The first case makes sense, not sure why the 2nd can't find `core` but trying to find out

**Comment by mkaput** [comment]
Yep, your findings are correct

**Comment by mkaput** [comment]
Updated issue description with a new vision of how this should work

**Comment by mkaput** [comment]
@tarrencev I think nobody is forking `core` any more? Therefore, I think we can freely abandon this feature as it is rather exotic and probably does not make sense now...
