### ISSUE TITLE
feat: add codespell linter tool for CI

### ISSUE THREAD

**Issue by xiaolou86** [software-mansion/scarb#922]
### Problem

Codespell linter tool is very important for code and system quality.

Sometimes, because of typo error, the system will go to bad and even crash, and take us much time to debug...

### Proposed Solution

So I want to add codespell linter tool for CI.

**Comment by mkaput** [comment]
Please don't, we are not going to accept such things in our CI.

**Comment by xiaolou86** [comment]
@mkaput Yes. But I just want to add codespell workflow in CI for convenience.
Could you help me to review the [PR](https://github.com/software-mansion/scarb/pull/923)
