### ISSUE TITLE
Cairo-run should not build the package

### ISSUE THREAD

**Issue by piwonskp** [software-mansion/scarb#983]
### Problem

Docs: 
> The scarb cairo-run command executes the main function of a local package. It does not compile any cairo code within the package so using scarb build beforehand is necessary.

(https://docs.swmansion.com/scarb/docs/extensions/cairo-run.html#using-cairo-run-in-scarb-projects)

Actual code:
https://github.com/software-mansion/scarb/blob/dc2e88b36e9109803cff222cf6197d4be0b33ff1/extensions/scarb-cairo-run/src/main.rs#L44

### Possible Solution(s)

I suggest removing the build from cairo-run as it would allow to run code compiled by custom plugins. Currently you have to reimplement both build and cairo-run to do that.

### Version

```text
2.3.1, also current main
```

**Comment by maciektr** [comment]
Hi!

Thanks for this report. We will update the docs and an option to skip build.
